pipeline:
  identifier: Build_java_sec_code_1696280365255
  name: Build java-sec-code
  orgIdentifier: default
  projectIdentifier: HARjavasec
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1695829315182
        repoName: java-sec-code
  stages:
    - stage:
        name: Analyze
        identifier: Analyze
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: SL Analyze
                  identifier: SL_Analyze
                  spec:
                    connectorRef: DOCConnectorjavasec
                    image: shiftleft/core:latest
                    shell: Sh
                    command: sl analyze --app HAR-java-sec
                    envVariables:
                      SHIFTLEFT_ACCESS_TOKEN: <+secrets.getValue("SLSecretjavasec")>
